### ISSUE TITLE
Add documentation tests to CI

### ISSUE THREAD

**Issue by aaronmondal** [TraceMachina/nativelink#1082]
To prevent issues like #1081 in the future.

While it's a bit tedious to create entire deployment pipelines, we should have at least run doc builds as a CI test. Preview builds already run the Typescript linting infrastructure and invoke the generator scripts on all inputs used which should cover a reasonably large surface area of potential issues.

**Comment by Evaan2001** [comment]
I'm working on this issue right now; PR should hopefully be up tomorrow, July 28th.

**Comment by Evaan2001** [comment]
Pull request is up – github.com/TraceMachina/nativelink/pull/1217. I'm failing a CI test. I edited the run_integration_tests.sh script and one of my comments seems to cause the failure. As this is my first time editing a CI pipeline, some feedback/direction would be great!
