### ISSUE TITLE
FilesystemStore should support native `StoreKey` instead of changing it to digest internally

### ISSUE THREAD

**Issue by allada** [TraceMachina/nativelink#1108]
Inside `FilesystemStore` we always turn the `StoreKey` into a digest, but in reality it should be using `.as_str()` for it's final destination storage name. This will make it much more usable for other future things (like BEP).

`MemoryStore` already has this optimization, so it can be used as a baseline on how to do this.

**Comment by MarcusSorealheis** [comment]
more guidance: https://gist.github.com/MarcusSorealheis/17307f41b6c632cb751c397280c70ed4

**Comment by KGrewal1** [comment]
Is there any greater specification for this? (eg how backwards compat should be handled / pitfalls from last 2 attempts?)

**Comment by MarcusSorealheis** [comment]
> Is there any greater specification for this? (eg how backwards compat should be handled / pitfalls from last 2 attempts?)

@KGrewal1 Welcome to NativeLink. Here is a high-level overview of contributing: https://github.com/tracemachina/nativelink/blob/main/CONTRIBUTING.md

It should be entirely backwards compatible. As in, an existing store configuration should work withNativeLink including this capability. It should be caught by the CI tests. 

There is also a design document required for the submission. Pitfalls from the first 2 attempts were no design document and too much reinvention of implementation. You should look at the structure of `MemoryStore` as a good reference for starting this work.

**Comment by MarcusSorealheis** [comment]
If you have any more questions I'll be happy to answer them here. We also have a Slack channel with a link on the website.

**Comment by KGrewal1** [comment]
Is there more guidance on how you prefer / what you want in design documentation (eg HackMD format or examples), and regarding lifetimes (were notes on both the previous PRs and the MemoryStore implementation), guess that is out of scope for this (as required by 'static bound on the map and so larger change as lots of 'static trait bounds as well) the Slack seems to be invitation only

**Comment by aleksdmladenovic** [comment]
/attempt https://github.com/TraceMachina/nativelink/issues/1108

**Comment by MarcusSorealheis** [comment]
The design document needs to be publicly viewable.

**Comment by KGrewal1** [comment]
https://hackmd.io/@HPxqrI77Q02izyGstTHbdg/ByS50OhGJx should be public now I think - re the CI run, seems stuck making pipelines for the local run

**Comment by KGrewal1** [comment]
Also re the lifetime issue for `get` I think this describes a way to do the workaround https://blinsay.com/blog/compound-keys/ at the end, but seemed out of scope for this and would need bikeshedding re type names

**Comment by KGrewal1** [comment]
Cheers, was really nice working with the NativeLink team on this!

**Comment by aaronmondal** [comment]
Closed by #1489
