### ISSUE TITLE
Lots of "failed to wait for awaited action to change" errors on main branch

### ISSUE THREAD

**Issue by cormacrelf** [TraceMachina/nativelink#1197]
Version = main branch. This happens quite frequently, but randomly. It's a bit more consistent for actions that take a bit longer, sometimes it will fail a few times in a row on the same action (one that takes about 3 minutes, and it fails after about 1 minute). Workaround is just to run the build again a few times and hope for the best (**or just go back to v0.4.0, which I have done**).

```
Failed to wait for awaited action to change 
Error { 
  code: Internal, 
  messages: [\"Failed to wait for awaited action to change RecvError(())\"] 
}: In SimpleSchedulerActionListener::changed getting receiver
```

This obviously comes from

https://github.com/TraceMachina/nativelink/blob/57987612547fa151a54a4b196671c0dcc3c15c5f/nativelink-scheduler/src/simple_scheduler.rs#L83-L87

https://github.com/TraceMachina/nativelink/blob/57987612547fa151a54a4b196671c0dcc3c15c5f/nativelink-scheduler/src/memory_awaited_action_db.rs#L154-L161

(And another place in that file)

I don't see any other useful logs that would tell us why the Sender half was dropped. But this comment in the lines just after the error sure seems like it's onto something:

https://github.com/TraceMachina/nativelink/blob/57987612547fa151a54a4b196671c0dcc3c15c5f/nativelink-scheduler/src/memory_awaited_action_db.rs#L180-L183

Configuration is basically what I described in https://github.com/TraceMachina/nativelink/issues/963, i.e. basic_cas.json with a couple of tweaks to paths / entrypoints etc. Buck2 is in the driver's seat.

**Comment by allada** [comment]
Thanks for the report, we detected this late yesterday as well. I believe we have identified the cause and I'll try to push a fix in a bit.

It has to do with the scheduler refactor recently. When a client disconnected then reconnected, it would not hold the connection alive as active and eventually it'd get cleaned up, causing down-stream listeners to get disconnected and close the stream.
