### ISSUE TITLE
Document development on NixOS

### ISSUE THREAD

**Issue by aaronmondal** [TraceMachina/nativelink#1229]
We support development on virtually every distribution since we ship our entire development environment with nix.

Ironically, the one distro that doesn't work out of the box is NixOS due to various assumptions on posix compliance. We should document how to set up the nativelink repo on NixOS.

cc @jaroeichler

**Comment by jaroeichler** [comment]
Working on this. I'll probably just have to figure out the right environment variables for nix-ld here.

**Comment by MohamadElgendy23** [comment]
> Working on this. I'll probably just have to figure out the right environment variables for nix-ld here.

Did you manage to complete this? I was going to work on it or at least continue where you left off on my own branch.
