### ISSUE TITLE
NativeLink version is not displayed correctly when it's built with Bazel

### ISSUE THREAD

**Issue by aleksdmladenovic** [TraceMachina/nativelink#1257]
Currently, when we build the application with `Bazel`, `--version` command doesn't work.
It works when the application is built with `Cargo` though.

![error](https://github.com/user-attachments/assets/2a6e2664-3950-495f-befa-e37ce1e55612)

The reason is because of this.

`clap` library gets the version information from the `CARGO_PKG_VERSION` environment variable.
https://docs.rs/clap_builder/4.5.14/src/clap_builder/macros.rs.html#16

Unfortunately, that variable is only set when the application is built with `Cargo`.
I've tried to pass that `CARGO_PKG_VERSION` environment variable explicitly via `.bazelrc` file but it didn't work.

The easiest way to solve this issue is to declare the version explicitly here in `nativelink.rs`.

https://github.com/TraceMachina/nativelink/blob/7777938294047377cb4ce9f4d8649c45055596ed/src/bin/nativelink.rs#L99

**Comment by aleksdmladenovic** [comment]
I will open a PR for it.

**Comment by allada** [comment]
Per: https://github.com/TraceMachina/nativelink/pull/1258#pullrequestreview-2231116848

We are currently considering this intended behavior, but thanks for the report :-)
