### ISSUE TITLE
Show warning when redis store fails to connect

### ISSUE THREAD

**Issue by zbirenbaum** [TraceMachina/nativelink#1266]
Currently it seems that nativelink will fail silently if it fails to connect to a given redis uri for a `RedisStore`. Instead, an error should be displayed when an attempt to upload or download data from the store does not execute.

**Comment by TheInvincibleRalph** [comment]
@aaronmondal I'd need a reference to the code directory/file for inspection

**Comment by vkobinski** [comment]
I'm going to work on this issue.

**Comment by harada1031** [comment]
I have ran the project according to guide but it doesn't fail even I give wrong uri in redis.json.
plz kindly let me know if I did wrong.
![Capture](https://github.com/user-attachments/assets/9451df66-aa4a-4da5-9e3c-a70ef744f17f)
