### ISSUE TITLE
Use docker to create a buck2 image

### ISSUE THREAD

**Issue by adam-singer** [TraceMachina/nativelink#1274]
Experiment with layering nix on top of ubuntu for toolchain image.

**Comment by SchahinRohani** [comment]
I have refactored the flake to make such experiments more accessible and well organized.

But it depends on another PR because of a few pkgs for web dev, but you can see the Draft PR here #1279.

**Comment by adam-singer** [comment]
> I have refactored the flake to make such experiments more accessible and well organized.
> 

Awesome, I can wait until this is ready, @aaronmondal is in the loop for https://github.com/TraceMachina/nativelink/pull/1279 ? 

> But it depends on another PR because of a few pkgs for web dev, but you can see the Draft PR here #1279.
 👍
