### ISSUE TITLE
Fix unpinned hashes in recent GHA workflow changes

### ISSUE THREAD

**Issue by aaronmondal** [TraceMachina/nativelink#1297]
These two need to be addressed:

- https://github.com/TraceMachina/nativelink/blob/689d099460fb9ce07e27b16bc02c117a13604c66/tools/toolchain-nativelink/Dockerfile#L33
- https://github.com/TraceMachina/nativelink/blob/689d099460fb9ce07e27b16bc02c117a13604c66/.github/workflows/main.yml#L31-L31

See also:

- https://github.com/TraceMachina/nativelink/security/code-scanning/32
- https://github.com/TraceMachina/nativelink/security/code-scanning/33

**Comment by aaronmondal** [comment]
Hmm it seems like OSSF still doesn't like the dockerfile implementation: https://github.com/TraceMachina/nativelink/security/code-scanning/34

**Comment by bclark8923** [comment]
@aaronmondal do we choose what version of OpenSSF we're running? A bug related to this was fixed last year 

https://github.com/ossf/scorecard/pull/3694

**Comment by aaronmondal** [comment]
Oh this is a good point! IIRC we haven't updated the scorecard action in quite a while. Updating it might fix this issue (and even if it doesn't, it's still a desirable change).

**Comment by aaronmondal** [comment]
Ok our scorecard version is almost certainly the issue here. I'll close this issue in favor of https://github.com/TraceMachina/nativelink/issues/1329
