### ISSUE TITLE
Store trait APIs should use u64 instead of usize

### ISSUE THREAD

**Issue by allada** [TraceMachina/nativelink#1328]
We currently use `usize` for the APIs in `StoreLike`, but they should be `u64`. It would be nice to move these all to use `u64` instead. This is because `u64` expresses the size of the data, but `usize` expresses local memory limits.

This will be a big PR, but mostly cosmetic with some `as usize` and `as u64`'s and/or `usize::try_from()` and `u64::try_from()`'s added and removed.

**Comment by aleksdmladenovic** [comment]
I will solve this issue.

cc: @allada, @MarcusSorealheis
