### ISSUE TITLE
Mermaid diagram no longer works in documentation

### ISSUE THREAD

**Issue by aleksdmladenovic** [TraceMachina/nativelink#1390]
All `mermaid` diagram is not working now.

Example Link: https://www.nativelink.com/docs/explanations/architecture

![2024-10-02_22-32-23](https://github.com/user-attachments/assets/f7471cb3-8d2b-4cca-af78-fa21d2e01613)

**Comment by aleksdmladenovic** [comment]
cc: @allada, @MarcusSorealheis, @blakehatch, @SchahinRohani

**Comment by aaronmondal** [comment]
Seems to be fixed: https://www.nativelink.com/docs/explanations/architecture
