### ISSUE TITLE
Test NativeLink with Buck2

### ISSUE THREAD

**Issue by allada** [TraceMachina/nativelink#222]
Buck2 has potential for gaining a lot of adoption quickly. They seem to make BRE a first-class-citizen, so we should test to ensure TruboCache can fully build Buck2 on Buck2.

If all passes, we should make an upstream patch to add TurboCache to their examples:
https://github.com/facebook/buck2/tree/main/examples/remote_execution

**Comment by allada** [comment]
In testing Buck2, things seem to be working. Buck2 does hammer the service for all it has though. From this testing I did discover a bug where too many file descriptors could be opened and end up blocking each other resulting in a deadlock.

A fix is en route #239.

The other minor bug I found is that buck2 does not send a `PATH` env. I'm going to make a simple env injector for the worker in a followup PR to solve this issue.

**Comment by aleksdmladenovic** [comment]
I've made PR draft for this issue to Buck2 repo.
https://github.com/facebook/buck2/pull/658

cc: @allada , @MarcusSorealheis

**Comment by aleksdmladenovic** [comment]
Hope you to close this PR since it's merged to buck2 repo.

https://github.com/facebook/buck2/pull/658

**Comment by adam-singer** [comment]
@aleksdmladenovic thank you for handling this!
