### ISSUE TITLE
Add official nix package

### ISSUE THREAD

**Issue by aaronmondal** [TraceMachina/nativelink#234]
As the project matures and gets closer to an actual release version we should start considering packaging options. One such option (that I'm most interested in :laughing:) is the nix package repository.

@allada Plz ping me when we're getting close to a release and I can prepare a nixpkgs release for turbo-cache. Apart from maybe a CI workflow this probably doesn't require a PR to this repo, just one to nixpkgs.

**Comment by allada** [comment]
Yeah, I think we could do some bundles soon. As for official releases, I would probably prefer to hold off a little longer. I want to avoid changes to the config file structure and feel that there's a couple features that might break the config format a under specific scenarios. But yeah I think we could pin a version, I would deem the code as of late pretty stable.

**Comment by aaronmondal** [comment]
Well, this has resolved itself :laughing:
