### ISSUE TITLE
Implement Redis store

### ISSUE THREAD

**Issue by allada** [TraceMachina/nativelink#302]
Looking at some stats it looks like a very significant portion of data is small and might be most optimally stored in redis.

We should implement a redis backend. This would pair well with a SizeDistinguishing store.

**Comment by blakehatch** [comment]
Going to take a stab at this one. Is there a certain threshold that’s known for what’s optimally small for Redis or is it a looser prediction from looking at the stats?

**Comment by blakehatch** [comment]
Also should I write an integration test for pairing SizePartitioning store with the Redis store?
