### ISSUE TITLE
Windows Cargo Test Frequently Runs Forever

### ISSUE THREAD

**Issue by MarcusSorealheis** [TraceMachina/nativelink#350]
Here are some recent examples:

[README change](https://github.com/TraceMachina/turbo-cache/actions/runs/6681385618/attempts/1)

[TLS Integration Tests](https://github.com/TraceMachina/turbo-cache/actions/runs/6679302673/attempts/1?pr=316)

**Comment by MarcusSorealheis** [comment]
[here's one with debug enabled](https://github.com/TraceMachina/turbo-cache/actions/runs/6681385618/attempts/3)

**Comment by aaronmondal** [comment]
Fixed by #525. Although @allada and I were not sure whether it's really fixed. Let's reopen in case this becomes an issue again.
