### ISSUE TITLE
Implement Completeness Checking Store

### ISSUE THREAD

**Issue by blakehatch** [TraceMachina/nativelink#362]
Implement other store (#357 is other store) for full Action Cache Validator functionality
- Checks does this exist in the item recently and caches existence bool
	- Doesn't store item in memory
	- Checks if requested recently
	- Pairs nicely with the existence caching
- Might be able to configure with digest -> boolean hashmap in memory store
	- Make optional in memory store

**Comment by allada** [comment]
It doesn't look like this change landed yet. Maybe mistakenly closed?

**Comment by blakehatch** [comment]
Yes mistakenly closed
