### ISSUE TITLE
Prometheus Complete Overhaul

### ISSUE THREAD

**Issue by blakehatch** [TraceMachina/nativelink#384]
Should migrate to [otel](https://opentelemetry.io/) and target for after 0.3.0

**Comment by adam-singer** [comment]
In this context it might be worth watching https://github.com/tokio-rs/tokio-metrics. Currently the package is marked as unstable so I think we should avoid it, the building blocks and runtime support does match the async framework we use. Probably should be a separate issue to be filed on it, but re-eval when we look at metrics again.
