### ISSUE TITLE
VerifyStore should support Blake3

### ISSUE THREAD

**Issue by allada** [TraceMachina/nativelink#444]
Currently VerifyStore is Sha256 specific. We should make this store support different digest functions.

see: https://github.com/TraceMachina/native-link/issues/191#issuecomment-1839543501
and:
https://github.com/TraceMachina/native-link/blob/f9e537c3f9b5656be6251902640ff003a5b8cc48/native-link-store/src/verify_store.rs#L140

**Comment by steed924** [comment]
I'd like to work on this issue.
