### ISSUE TITLE
RunningActionsManager's `kill_all_waits_for_all_tasks_to_finish` test never ends on Windows x64

### ISSUE THREAD

**Issue by steed924** [TraceMachina/nativelink#492]
While I was testing on Windows x64 machine, I found out that `running_actions_manager_tests::kill_all_waits_for_all_tasks_to_finish` test never ends when I test with `cargo test --all` command.
They used to be working fine when I test on my Linux machine.
On the other hand, the similar test which has a platform specific code `running_actions_manager_tests::worker_times_out` is working great.

![Capture](https://github.com/TraceMachina/nativelink/assets/93139780/612ff919-96b7-4807-a237-8de830f5730f)

**Comment by aaronmondal** [comment]
This has been a long-standing issue in CI. If I remember correctly either this issue or something similar was reproducible on linux by uncommenting these lines:

https://github.com/TraceMachina/nativelink/blob/96302cbeab6c59966d3dfd3b99fa0933752d1018/flake.nix#L113-L120

**Comment by steed924** [comment]
Hi, @aaronmondal .
FYI, decreasing this number from 1000 to 500 seems to fix the problem on my machine.
It seems like too many iterating made our tests not to finish on Windows x64 machine.
Is it okay to make PR to decrease this numer to 500?


https://github.com/TraceMachina/nativelink/blob/a18d2d2a9e1a1d1ca5f77c305e948d62e7c4a2e1/nativelink-worker/tests/running_actions_manager_test.rs#L2511

![Capture](https://github.com/TraceMachina/nativelink/assets/93139780/94600910-b683-4321-9306-18357ae9775d)
