### ISSUE TITLE
Empty digests not handled properly

### ISSUE THREAD

**Issue by allada** [TraceMachina/nativelink#498]
We don't quite follow remote execution spec here: https://github.com/TraceMachina/nativelink/blob/e1c495fa68b5d85872c98f9231689da4581161b1/nativelink-proto/build/bazel/remote/execution/v2/remote_execution.proto#L333

The easiest way to handle this would probably be to simply check/upload an empty digest of every support digest hash function at startup.

Finding the right place to put this feature seems a bit more complicated.

**Comment by adam-singer** [comment]
@allada can we implement the defaulting logic of empty digests in https://github.com/adam-singer/native-link/blob/e1c495fa68b5d85872c98f9231689da4581161b1/nativelink-util/src/store_trait.rs#L43 with `is_empty_digest` and proceed to return successful responses before calling the underlying store?
