### ISSUE TITLE
CI Does Not Update Dependency Versions

### ISSUE THREAD

**Issue by MarcusSorealheis** [TraceMachina/nativelink#504]
See the failure here: https://github.com/TraceMachina/nativelink/actions/runs/7254007633/job/19761818356?pr=502

In this run, the CI fails because the environment loads a library version being replaced by the PR itself. This is an error. We should `clean` or take whatever steps appropriate to provision CI runners with the appropriate versions.

**Comment by aaronmondal** [comment]
False positive. Already documented here:

https://github.com/TraceMachina/nativelink/blob/main/CONTRIBUTING.md#updating-rust-dependencies
