### ISSUE TITLE
Bazel run doesn't work on local machine - Ubuntu 22.0.4

### ISSUE THREAD

**Issue by steed924** [TraceMachina/nativelink#582]
I tried to do an extensive testing on my local VPS machine which is Ubuntu 22.0.4 installed.
When I ran the `nativelink` application with `cargo run` command, it works out well and `bazel test` ran successfully.
But I try to run the application with `bazel run` command, it shows the following message.
I think the application says it can't load the config file.
Maybe the path settings issue?
I followed the default steps which is mentioned in the documentation and I wonder what external settings I have also.
[](url)
![Capture](https://github.com/TraceMachina/nativelink/assets/93139780/24576bcc-6bfb-4644-a2d8-27f80069f443)

**Comment by aaronmondal** [comment]
I can reproduce. The following work:

```
bazel run nativelink $(pwd)/nativelink-config/examples/basic_cas.json 
bazel run nativelink ~/some/subdir/nativelink-config/examples/basic_cas.json
bazel run /absolute/path/to/basic_cas.json
```

But the `./` syntax doesn't. I'm not sure whether we should flag this as a bug or as incorrect documentation. The `./` syntax seems kind of odd to me since we're not "invoking" the config file. I don't think we should support that usecase (and apparently we never did, so removing this from the docs wouldn't be a breaking change :sweat_smile:)

Another example that doesn't work is `nativelink-config/examples/basic_cas.json` without any leading symbols. I believe this is what we actually want.

**Comment by MarcusSorealheis** [comment]
Good catch @steed924 and thank you for reproducing. Can you link to where this command is documented or open a PR to remove it so we can resolve quickly?

**Comment by MarcusSorealheis** [comment]
cc @blakehatch

**Comment by adam-singer** [comment]
Updating documentation/code points is appropriate. The reason for this is that `bazel run` current directory is the bazel out/runfiles, it is a common trip up (https://github.com/bazelbuild/bazel/issues/2579#issuecomment-626840214, https://github.com/bazelbuild/bazel/issues/3325, [Bazel + C++ project: how to specify working directory for 'run' command](https://stackoverflow.com/questions/70256713/bazel-c-project-how-to-specify-working-directory-for-run-command)). There are a few ways to deal with it depending on the context of what is being run. Absolute paths is generally the easiest way, depending on how deep or relative the paths to expand are, might be cumbersome.  Embedding [resources / data](https://jayconrod.com/posts/108/writing-bazel-rules-data-and-runfiles) fields for bazel `BUILD` is common, usually good for things that have resource resolvers where everything is relative (such as jvm or transpiled code). Last option I can think of is using [--run-under](https://bazel.build/docs/user-manual#run_under) , it allows for arbitrary script prefix, so one could `cd` into a new directory of choice (such as the root of a project).

In cases where bazel is not executed from the root of a repo, the following command is a slightly more precise, but `$(pwd)` should be simple enough.

```
bazel run nativelink $(git rev-parse --show-toplevel)/nativelink-config/examples/basic_cas.json
```
