### ISSUE TITLE
Rejoining streams tracks what last byte received is racy

### ISSUE THREAD

**Issue by allada** [TraceMachina/nativelink#587]
When users rejoin streams after a disconnect the query can respond with the wrong number of bytes received. This is very rare and the backend rejects the clients from sending the data due to other checks, so there's no poisoning happening, however it sometimes causes clients to fall over.

**Comment by MarcusSorealheis** [comment]
Users might see a message like this: message: `"Received out of order data. Got 1
7793024, expected 17825792 : In ByteStreamServer::write()"`

**Comment by chrisstaite-menlo** [comment]
Pretty sure I fixed this in #635
