### ISSUE TITLE
Autogenerate docs from existing READMEs

### ISSUE THREAD

**Issue by aaronmondal** [TraceMachina/nativelink#594]
Syncing documentation manually is a tedious, error prone task.

Since we have Docusaurus with per-commit deployments it should be fairly straightforward to auto-sync all information from the READMEs.

Related: #593

**Comment by blakehatch** [comment]
Should we have a subset of READMEs that get synced with the docs? Deployment examples are 1:1 but quickstart is intentionally not 1:1 and takes advantage of mdx features.

**Comment by aaronmondal** [comment]
> Should we have a subset of READMEs that get synced with the docs? Deployment examples are 1:1 but quickstart is intentionally not 1:1 and takes advantage of mdx features.

SGTM. I think the most important thing at the moment is to have any sort of syncing at all. We can always exempt certain files if it makes more sense like that.

**Comment by aaronmondal** [comment]
Fixed by
- #1056
