### ISSUE TITLE
Filesystem store size should take disk block size into account

### ISSUE THREAD

**Issue by allada** [TraceMachina/nativelink#595]
Current filesystem store takes only the size of the content into account, not the disk block size. It should compute the apx block size it'll use as a config and use it for size on disk eviction policies.

**Comment by zbirenbaum** [comment]
I've been working on this and had a couple quick comments/questions:

I believe the easiest way to do this is to override the len function in LenEntry inside `filesystem_store` to return the amount padded to a block size multiple. It seems to work, but breaks some tests.

1. Would the relevant block size be the disk block size or the filesystem block size? Either way 4KB is the standard, but if reading it from somewhere is important then this becomes relevant. There should be a way to manually override this value for the reasons listed in (2) though.
2. When max_bytes for the eviction policy is less than the block size, insert operations will hang. I think the best way to prevent this would be to have a `block_size` field in the config and pass in a number during the tests. Setting the default to 1 should retain current behavior without changes, but the default block size for every filesystem I know of is 4KB so I'm not sure that's the best option.

**Comment by allada** [comment]
I agree that using the formula of something like `ceil(item_size / block_size) * block_size` seems like the best approach, it's not perfect but should get us close to what reality is.

1. I think filesystem size is most appropriate, but to be honest it might be easiest to default it to 4KB and make it a config. Otherwise we'll need to bring in OS specific headers to sniff it out.
2. I don't think we should worry about crazy configs like `max_bytes > block_size`, maybe assert it if concerned.

In general I like the approach though. I always prefer to write code to make it easier to test, so your approach is spot on :-)

**Comment by zbirenbaum** [comment]
> I agree that using the formula of something like `ceil(item_size / block_size) * block_size` seems like the best approach, it's not perfect but should get us close to what reality is.
> 
> 
> 
> 1. I think filesystem size is most appropriate, but to be honest it might be easiest to default it to 4KB and make it a config. Otherwise we'll need to bring in OS specific headers to sniff it out.
> 
> 2. I don't think we should worry about crazy configs like `max_bytes > block_size`, maybe assert it if concerned.
> 
> 
> 
> In general I like the approach though. I always prefer to write code to make it easier to test, so your approach is spot on :-)

Sounds good, thanks for clarifying and glad to know I'm on the right track!
