### ISSUE TITLE
Scale back use of `async-trait` where applicable

### ISSUE THREAD

**Issue by aaronmondal** [TraceMachina/nativelink#620]
Since Rust 1.75.0 the language has native support for `async fn` in Traits for some usecases (https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html).

Dynamic dispatch isn't supported yet (https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html#dynamic-dispatch), meaning that a full removal of the `async-trait` dependency might not be possible at this point.

However, I believe that some uses of `aysnc-trait` in the NativeLink codebase have become redundant. Removing them is a reduction in complexity and a potential performance improvement.

**Comment by adam-singer** [comment]
cc: Assigned to @jhpratt
