### ISSUE TITLE
Need easier way to evict/specify s3 bucket/prefix on item level

### ISSUE THREAD

**Issue by allada** [TraceMachina/nativelink#622]
Clearing S3 cache can take quite a long time, it would be super useful if the client can just target a new S3 bucket/prefix just in case cache gets poisoned or for testing a small change on the client side could quickly fix it.

One idea:
Allow `instance_name` to be used as a prefix to the s3 store. This would allow users to change the `--instance_name` property at invocation time (client/bazel) side and the s3-config would be able to use it as part of the prefix.

**Comment by steed924** [comment]
I'd like to work on this issue. cc: @allada , @MarcusSorealheis .

**Comment by MarcusSorealheis** [comment]
@steed924 sgtm

**Comment by allada** [comment]
This is a bit our of scope, we do have a way to prefix s3 store and we now refresh items automatically with a config.
