### ISSUE TITLE
Slow store not checked for has

### ISSUE THREAD

**Issue by chrisstaite-menlo** [TraceMachina/nativelink#628]
When running a proxy CAS I found that if writing to the slow store failed, if it came to check later it says that the file is there because it's in the fast store, but it's not in the slow store, which means that the execution fails with workers pointing at the main CAS.

**Comment by allada** [comment]
Fixed https://github.com/TraceMachina/nativelink/commit/f9f79085ac279327428cedda0921aca517c30a7f
