### ISSUE TITLE
Factor out health status checks to it's own service file

### ISSUE THREAD

**Issue by allada** [TraceMachina/nativelink#643]
Right now health status checks are not a proper service and instead done [here](https://github.com/TraceMachina/nativelink/blob/29604699d0475357a23007d4192da4b0f3c78857/src/bin/nativelink.rs#L406).

What we should do is have this be it's own [service](https://github.com/TraceMachina/nativelink/tree/main/nativelink-service).

**Comment by blizzardc0der** [comment]
I'd like to work on this task. cc: @allada
