### ISSUE TITLE
Achieve metrics coverage on stores

### ISSUE THREAD

**Issue by blakehatch** [TraceMachina/nativelink#650]
The stores that are missing metrics are:
- [x] Completeness Checking Store
- [x] Dedup Store
- [x] Grpc Store
- [x] Noop Store
- [x] Ref Store
- [x] S3 Store
- [x] Size Partitioning store

**Comment by aaronmondal** [comment]
Not saying I'm against implementing it in the current infra, but I want to mention that this could be a waste of time to implement in our current setup. If we do this now we'll need to port all those metrics over to the `otel-subscriber` later. If we migrate to `otel-subscriber` first and change the `log`, `error`, `info` etc messages to the more idiomatic instrumentation syntax we get all these metrics for free.

**Comment by blakehatch** [comment]
Oh wow I actually didn't know otel gives us metrics through logging that's really nice.
Will leave this here for now as a reference for which stores have metrics currently for cloud and which don't then we can close this issue along with the otel migration.

**Comment by MarcusSorealheis** [comment]
Is this still an issue? Cc @blakehatch
