### ISSUE TITLE
Readme says to use `basic_cas.json` in wrong directory

### ISSUE THREAD

**Issue by allada** [TraceMachina/nativelink#668]
The readme in nativelink says to start it with:
```
nativelink basic_cas.json
```

But this won't work because that is not where the `basic_cas.json` file lives.

see:
https://github.com/TraceMachina/nativelink?tab=readme-ov-file#start-nativelink

**Comment by MarcusSorealheis** [comment]
We do say in some places in the docs to curl for the file just after compiling the executable. I need to check all the READMEs.

**Comment by allada** [comment]
I see, in that case i think we should combine these two steps into one and have two lines... one to download the file and the other to use it, but in the same shell section.
