### ISSUE TITLE
Update Local Remote Execution README

### ISSUE THREAD

**Issue by blakehatch** [TraceMachina/nativelink#672]
Some additional instruction/dependencies for using LRE on a fresh machine are:
1. Needs to be run on a linux (ex ubuntu) machine
2. Needs a policy file
3. Needs docker.io with root access

To create a policy file run:
```shell
mkdir -p /etc/containers && sudo vi /etc/containers/policy.json
```

Then set the file contents to something like (This may be an unsafe configuration for a native work/personal machine, use caution when outside of a safe environment like an EC2 instance):
```json
{
  "default": [
    {
      "type": "insecureAcceptAnything"
    }
  ]
}

```

**Comment by MarcusSorealheis** [comment]
I'm not going to add `"insecureAcceptAnything"` to our repo without a lot of caveats. I'll think a policy file that is really easy for customers but doesn't cause problems.

Maybe the middle ground is that I can add a note further down with a more secure policy file or link to the policy file docs.

**Comment by bclark8923** [comment]
This should be re-defined as an internal only tool

**Comment by aaronmondal** [comment]
LRE docs have been updated/made more precise and we added warnings that it's highly experimental tech. Closing for now - we can reopen if additional issues pop up.
