### ISSUE TITLE
Prepare Release `0.3.0`

### ISSUE THREAD

**Issue by MarcusSorealheis** [TraceMachina/nativelink#674]
There are a number of additions that need to be cherrypicked into the next release of NativeLink. We can enumerate them here later as we define them, but creating the ticket for tracking.

**Comment by aaronmondal** [comment]
Yeah we really want to create a new release soon. One thing I'd like to get in is that we also start publishing toolchain containers and clean up the toolchain generation logic a bit (including improving the docs). ATM this seems to be the thing that has the most impact on ease of adoption and it's fairly straightforward to fix.
