### ISSUE TITLE
Unify `validate_output` logic in `CompletenessCheckingStore` and `CacheLookupScheduler`

### ISSUE THREAD

**Issue by allada** [TraceMachina/nativelink#677]
It looks like we have duplicated work here. We should probably just require `CacheLookupScheduler` to be pointed to a `CompletenessCheckingStore` to simplify the logic.

fyi: @blakehatch, @chrisstaite-menlo

**Comment by blizzardc0der** [comment]
cc: @allada

**Comment by adam-singer** [comment]
@blizzardc0der please take it on, you can reach out to me with any questions
