### ISSUE TITLE
Improve Configuration Breakdown Documentation

### ISSUE THREAD

**Issue by blakehatch** [TraceMachina/nativelink#681]
Document these example configuration files, if not created place them in a deployment example:

- `cas.json`
- `scheduler.json`
- `nl-cas.yaml`
- `nl-scheduler.yaml`

The explanations must hinge around enabling third parties to effectively customize these configs for their specific use-cases when making their own deployments.

The documentation of these files must adhere to a quality standard meeting this: [config documentation example](https://www.mongodb.com/docs/kubernetes-operator/stable/tutorial/deploy-replica-set/#change-the-settings-to-your-preferred-values)

**Comment by aaronmondal** [comment]
Fixed by:

- #1056
