### ISSUE TITLE
Health Check Service for Native Link

### ISSUE THREAD

**Issue by DolceTriade** [TraceMachina/nativelink#757]
It would be nice if nativelink supported a basic health check for liveness checks in kubernetes/envoy/etc.

It seems Nativelink already has healthchecks for its stores. If we could propagate that into either a simple HTTP /healthz endpoint (maybe on the admin port?) or implement https://crates.io/crates/tonic-health on one of the gRPC ports, that would be ideal.

Can be configurable via services in the nativelink config.

Happy to take a stab at a PR if it seems like a desirable thing and we can agree on the mechanism.

**Comment by adam-singer** [comment]
@DolceTriade the initial `/status` route is being used for checking health in some context. The plan is to map the internal meaning of health to the external systems that would query for it. `/healthz` for kubernetes (and other systems) I assume work the same where any route could be used and what matters is status code responses (at least thats what I've gathered from documentation). There are specifications that allow for query parameters to filter out health checks by some mappings. We don't have any gRPC port checking atm, I think `tonic-health` would be a good starting point on that side. 

Please take a stab at it or we can discuss more on details for the external to internal mappings of what health could mean.

**Comment by DolceTriade** [comment]
Hm, I didn't know about the /status admin endpoint. That's probably sufficient for my use cases. we can probably close this unless the gRPC check is important.

**Comment by allada** [comment]
Yeah, when https://github.com/TraceMachina/nativelink/issues/643 is done, it should help discoverability.
