### ISSUE TITLE
Rustup on windows CI runner is flaky

### ISSUE THREAD

**Issue by aaronmondal** [TraceMachina/nativelink#773]
The `Cargo Native / windows-2022` workflow sometimes instafails due to some unknown rustup issue. This could be caused by changes to GHA runners that we have no control over. Either way, it's confusing to see this CI run fail and we should look for a solution.

Example: https://github.com/TraceMachina/nativelink/actions/runs/8302042001/job/22740450140

**Comment by MarcusSorealheis** [comment]
For now, it would be good to have it run but on a non-main, non-release branch. So few people will be using non-UNIX based systems for now.

**Comment by aaronmondal** [comment]
See https://github.com/rust-lang/rustup/issues/3189
