### ISSUE TITLE
a way to configure env variables that should be passed down to the spawned worker process

### ISSUE THREAD

**Issue by vors** [TraceMachina/nativelink#819]
I have the following scenario.
My tests need to access azure blob storage (I understand that this is not ideal, but that's how it is).
In order for this to work I need to pass down env vars
AZURE_CLIENT_ID
AZURE_CLIENT_NAME
AZURE_CLIENT_SECRET
into the spawned test process from the `nativelink` launch script.

Currently there is no way to do it with `nativelink`.
The implementation could be an optional list env variables to pass from the host process.
I can work on the patch if this direction sounds good.

**Comment by allada** [comment]
Currently this could be done in the json using `additional_environment` field for the worker.

Something like:
```json5
{
  ...
  "workers": [{
    "local": {
      ...
      "additional_environment": {
        "AZURE_CLIENT_ID": {
          "value": "${AZURE_CLIENT_ID:-default_value_can_go_here}"
        },
      },
      ...
    },
  }],
  ...
}
```

Let me know your current config and I can help populate it further if the above example is giving you trouble.

**Comment by vors** [comment]
Ah amazing! Will give it a shot soon.

**Comment by allada** [comment]
If this did not resolve the issue please feel free to reopen this issue :-)
