### ISSUE TITLE
[Discussion] How to handle upload retries

### ISSUE THREAD

**Issue by allada** [TraceMachina/nativelink#824]
# Problem
Retry of uploads can be very tricky depending on what the target store is. Most (all?) stores do not have upload retry logic in place and when dealing with stores that xfer data over network this is problematic.

## Details
We spend a lot of effort to try not to hold data in memory while it is being transferred. Most all places data is simply shipped from one-place to another with some small buffers for efficiency. The reason for this is to ensure we don't end up running out of memory.

## Idea 1
We could make a new store who's job is simply to retry uploads with some internal buffer on how much total upload buffer is allowed. When the buffer per request is exceeded, it'll consider the request no longer retryable, since it will still be feeding data to the underlying store, but the head of the upload data will have been lost.

## Idea 2
We could make each store (S3) hold a buffer internally for the uploads and retry them inside the specific stores that need full-upload-retries. This is the same as 1, but specific to each store.

**Comment by adam-singer** [comment]
Do clients need to know of upload failures on the upload path or do they find out when trying to fetch an uploaded artifact?

Do we want to retry with blocking on response or to defer with retry? Example of defer with retry is using async queues or queue systems that use the queue as the memory buffer (kafka/redis/etc).

**Comment by allada** [comment]
> Do clients need to know of upload failures on the upload path or do they find out when trying to fetch an uploaded artifact?
No, the kind of retrying I'm talking about should be all behind the scenes. Bazel has some retry capability, but that is very client specific. In reality, if we get an error on upload due to a TCP connection breaking or maybe a node going down, we should retry on behalf of the client if possible.

> Do we want to retry with blocking on response or to defer with retry?
We already block on response during an upload (it's part of the spec), so yes block the response until it finishes.
