### ISSUE TITLE
Quantity fields should be human-readable

### ISSUE THREAD

**Issue by aaronmondal** [TraceMachina/nativelink#862]
Instead of this:

```json
"eviction_policy": {
  // 50mb.
  "max_bytes": 50000000,
}
```

We could have this which seems more readable and is standardized in the [Kubernetes Quantity format](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/#Quantity):

```json
"eviction_policy": {
  "max_bytes": "50Mi",
}
```

**Comment by matdexir** [comment]
Hi @aaronmondal 

I was thinking of taking on this issue if still available.
Before proceeding, I was wondering: should it support both versions or only the human readable version?

**Comment by allada** [comment]
To be honest, I'd prefer to always use primitives (non-complex structs) in our config. Some day in the future there's a reasonable chance we'll need our structs to be FFI compliant, and using raw primitives is going to make things easier.

As for how to do this, I'd keep them as `u64` but make a custom `deserializer` in serde that can convert strings that have prefixes to an integer. For example, if we say:
```json5
{
  "size1": "5kB"
  "size2": "5KiB",
  "size3": "5GiB"
}
```

Would result in a struct like (respectively):
```rs
Data {
  size1: 1000,
  size2: 1024,
  size3: 1073741824,
}
```

It shouldn't be too difficult to make one that takes shell_expand and a suffix qualifier. I'd even argue we could probably convert what is already there and we wouldn't even need to create a new deserialization function for it.

**Comment by matdexir** [comment]
Hi,
Sorry for the late response! Didn't have enough time to dive into the issue.

Here's a sample of how I think it would go: [preview gist](https://gist.github.com/matdexir/8b0285a63ec744f55d76131de643149a)
_Note: I haven't written rust in months so it may not be very idiomatic._

For this use case I would only implement `deserialize` since I am unsure if `serialize` would be needed. 
My train of thought is:
```rust=
enum Unit {
 KiloBytes, // KB
 Kibibit, // KiB
 ....
}
struct Quantity {
  value: u64,
  unit: Unit,
}
```
Then implement deserialization accordingly, although, I do not think that keeping the unit would be of much value :thinking:.
What do you think?
cc: @aaronmondal, @allada

**Comment by allada** [comment]
This is pretty close to what I was thinking. There are a few minor differences, the struct's must use only FFI compatible primitives (String, Enum, u64, usize, float64, exc...).

I suggest using the following libraries that will do the conversion though. I'm pretty sure just wrapping these in a function should do much of the work:
https://docs.rs/humantime/latest/humantime/fn.parse_duration.html
https://docs.rs/byte-unit/latest/byte_unit/enum.Unit.html#method.parse_str

Thanks :-)

**Comment by aleksdmladenovic** [comment]
I would like to contribute on this issue. @allada @MarcusSorealheis @aaronmondal

**Comment by allada** [comment]
@matdexir, @aleksdmladenovic and us had a small conversation on slack. I assume you wanted to take this one on?

**Comment by aleksdmladenovic** [comment]
Yes, now I am working on the issue for reducing the verbosity of ping message.
https://github.com/TraceMachina/nativelink/issues/764
I would like to work on this issue after accomplishing #764.

**Comment by matdexir** [comment]
Hi @allada 
Yes I wanted to take this one on. I live in a GMT+8 timezone so there may be delay in my response.

**Comment by allada** [comment]
Thanks to both. @matdexir has already put work into it, so lets give some time for them to accomplish it.
