### ISSUE TITLE
Quickstart docs are outdated

### ISSUE THREAD

**Issue by chinchaun** [TraceMachina/nativelink#892]
Bazel version is outdated.
my 2 cents will be to concentrate the documentation in one place because the readme and the quickstark will keep drifting apart

**Comment by blakehatch** [comment]
Hi @chinchaun, thanks for the recommendation! We are planning on automating the process of keeping README and Quickstart in-sync. Also happy to have anyone work on that.

**Comment by aaronmondal** [comment]
Fixed by:

- #1127
