### ISSUE TITLE
Configuration Documentation Enhancement

### ISSUE THREAD

**Issue by MarcusSorealheis** [TraceMachina/nativelink#958]
Currently we do not document our configuration object sufficiently enough.

We need to accomplish three goals:

1) Break out each key and explain all the options, with a plan to update after refactoring the configuration object.

In the same way that there are some pages of deployment examples, we need a sub-page for each configuration key so that people can isolate what they need to understand if they choose to. For example, `experimental_promtheus` should also have its own sub-page explaining how it works. 

<img width="1267" alt="image" src="https://github.com/TraceMachina/nativelink/assets/2353608/52f5710e-1357-4669-bff1-99c517eaf408">

2) Provide a lot more configuration examples by use case.

In the same way that we `Deployment Examples`, we should also have `Configuration Examples`, such that the current `Configuration` should become `Configuration Options`. 

3) Include documentation in our docs for Buck2 and Reclient.

We also need a top level page for describing how you can use NativeLink with Buck2 and one for how you can use NativeLink with Reclient. For example, we need to include concepts like injecting `cpu_count` values for Reclient, as has appeared in the Slack.

**Comment by blakehatch** [comment]
Hi @MarcusSorealheis will take on the Buck2 portions of this. Will become two issues but will likely get landed around the same time and will reference this issue.
